navikt/familie-ef-personhendelse

src/main/kotlin/no/nav/familie/ef/personhendelse/client/AzureClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/client/PdlClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/client/SakClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandler.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandlerTest.kt
Hovedsaklig for å forbedre loggene, slik at kall får callId og consumerId
=> Bruk felles httpclient

.gitignore, pom.xml, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/DodsfallHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/KafkaErrorHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/converter/DateCoverters.kt, src/main/resources/pdl/schema.graphql, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/DodsfallHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandlerTest.kt
Lagt til converters og håndtering for string
Samt noen småjusteringer
Litt rart likevel att den wrapper LocalDate/LocalDateTime i egne typer, men vi unngår å håndtere de som strings i koden då :)
=> Finpusset litt på oppsettet av graphql og avro

.deploy/preprod.yaml, .deploy/prod.yaml
Legger til denne separat for "init" av postgres basen
=> Oppfører Nais postgres instans familie-ef-personhendelse

src/main/resources/application-dev.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-7659
=> Skrur om til å bruke q1 i dev

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt, src/test/resources/inntekt/InntekthistorikkInntektUnderHalvG.json
- Lager ikke oppgave dersom bruker har inntekt mindre enn en halv G
- Ignorerer etterbetalinger fra ytelser
=> Forbedringer av inntektsendringer:

src/main/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandler.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandlerTest.kt
=> Endrer beskrivelse for hendelser ifm barn som er født for tidlig

src/main/kotlin/no/nav/familie/ef/personhendelse/client/SakClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt
Testet i preprod. Antakeligvis ikke veldig mye raskere, men hindrer at det kræsjer på denne måten.
Relatert til: https://github.com/navikt/familie-ef-sak/pull/1427
Mangler opprydning for fjerning av personer i db der stønad har utgått.
=> Ytelseforbedring inntektsendringer

pom.xml, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandler.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandlerTest.kt
Merges etter https://github.com/navikt/familie-ef-sak/pull/1756
Favro-oppgave: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9399
=> Skriv ut stønadstype i oppgave som skal opprettes, dersom det er nytt barn

src/main/kotlin/no/nav/familie/ef/personhendelse/configuration/KafkaConfig.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakListener.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListenerAiven.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListenerTest.kt
Venter på tilgang til å lese fra topic i Aiven.
Skal bruke aiven-container factory når begge konsumentene er i sync med siste endring på topic
=> Leser fra topic i Aiven uten å gjøre noe.

src/main/kotlin/no/nav/familie/ef/personhendelse/client/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/DodsfallHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/DøfødtBarnHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/UtflyttingHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10490
Også fikset:
* Korrigerings-oppgaven legges i mappe 62
* VedtakendringerService burde ikke være avhengig av PersonHendelseService
* Litt mer logging
=> Korrigert dødsfall av barnet skal ikke opprette oppgave på barnet, men forelderen

.deploy/preprod.yaml, .deploy/prod.yaml, src/main/resources/application-dev.yml, src/main/resources/application.yml
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10604
=> Tar i bruk q2 og går bort fra felles secret

.github/workflows/build.yaml
Ny PR - gammelt workflow-steg hindret merge i forrige PR.
=> Build-script

pom.xml
Avhengigheten trengs ikke lenger, og kan fjernes går jeg ut ifra @blommish ?
=> Oppdaterer til spring versjon 3.1.0 og fjerner avhengighet som ikke brukes i spring 3 lenger

src/main/kotlin/no/nav/familie/ef/personhendelse/personhendelsemapping/PersonhendelseRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/util/OppgaveController.kt, src/main/resources/pdl/schema.graphql
**Hvorfor?**
Vi har blitt bedt om å ta et uttrekk av dødsfall-hendelser som vi har lagd oppgaver på.
=> Log opprettede oppgaver

src/main/kotlin/no/nav/familie/ef/personhendelse/util/OppgaveController.kt
Det er ikke mulig å søke på aktørid i ef-sak eller gosys
=> Skriver ut fødselsnummer i stedet for aktørid

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yaml
Får "installation not allowed to Write organization package", og trenger skrivetilgang for pakker
=> Skrivetilgang ved build and push

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektDomain.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/main/resources/db/migration/V8__lagre_belop_inntektsendring.sql, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
Det er et ønske om å se endring i beløp i tillegg til prosent. Denne merges og kjøres før: https://github.com/navikt/familie-ef-personhendelse/pull/441 - så mergekonflikter vil rettes i den andre branchen.
=> Inntektsendring: Lagre beløp for siste to måneder

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
AAP og dagpenger skal regnes som inntekt
=> Ta med AAP og dagpenger i beregning av samlet inntekt

src/main/kotlin/no/nav/familie/ef/personhendelse/client/SakClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt
Det er stadig behov for å endre hvor langt tilbake inntektsuttrekket skal gå. Parameteriserer antall måneder slik at det ikke er nødvendig å endre ef-sak hver gang antall måneder skal endres.
https://github.com/navikt/familie-ef-sak/pull/2444
=> Endepunkt for å hente personer med aktiv stønad er endret til å ha parameterisert antall måneder

pom.xml, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerScheduler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt
Oppretter oppgaver med ny oppgavetype vurder inntekt.
Uttrekket tas kl 4 den 6. hver måned, så oppgavene vil være klare rundt kl 06.30 hvis uttrekket kjører uten feil.
=> Inntektskontroll kjøres kl 4 den 6. hver måned.

pom.xml
7.5.2 introduserer feil, ref: https://nav-it.slack.com/archives/C84H68ESC/p1700556875004519
=> Reverter oppgradering av avro-serializer da det fører til serialiseringsfeil i prod

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerScheduler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml
Ser ut til at leader-sjekken ikke virket, og aldri ble true. Fjerner denne da personhendelse uansett bare kjører med en pod. Har ikke funnet ut av hvorfor leader-sjekken ikke virket.
=> Schedule inntektskontroll

.deploy/preprod.yaml, .deploy/prod.yaml
Feil i definering av db i nais.yaml.
=> Rettet nais.yaml til å være gyldig med strengere validering

README.md
Hvorfor ? 
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17892
=> Oppdaterer readme

pom.xml, src/main/kotlin/no/nav/familie/ef/personhendelse/configuration/ApplicationConfig.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kontantstøtte/vedtak/KontantstøtteVedtakListener.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kontantstøtte/vedtak/KontantstøtteVedtakService.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/IntegrasjonstestConfig.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/kontantstøtte/vedtak/KontantstøtteVedtakListenerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/kontantstøtte/vedtak/KontantstøtteVedtakRepositoryTest.kt, src/test/resources/application-integrasjonstest.yml
Tester i dev før merge.
Appen kjører ikke lokalt, og det ble derfor få endringer her.
=> Oppgraderer til token-support 4

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
Ved beregning av samlet inntekt skal feriepenger også tas med
=> Det er besluttet at feriepenger skal regnes som vanlig inntekt

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/AutomatiskRevurderingService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt
Løsner på kriteriet for personer som kan revurderes automatisk. Logger i prod for å teste om dette vil gjøre at en del flere personer kan revurderes, og hvor forventet inntekt kan beregnes automatisk.
=> Automatisk revurdering: Løsner på kravet til stabil inntekt

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektDomain.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerScheduler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/inntektv2/InntektV2Response.kt
Tester v2 av inntekt ved å logge om sum inntekt per pers blir lik som v1 ved kjøring av inntektskontroll.
=> Inntekt v2

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
Denne endringen gjør at de ikke sendes videre til automatisk revurdering i ef-sak.
=> Ett av kriteriene for at en bruker kan automatisk revurderes er at vedkommende ikke skal ha noen andre løpende ytelser

src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt
Vil fjerne noen logger fra personhendelse
=> Vil fjerne noen logger fra personhendelse

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/resources/application-dev.yml
Bugfix: Før ble nok ikke alle inntekter tatt med hvis det var flere arbeidsgivere
=> Tar høyde for at det finnes flere inntektlister pr måned

src/main/kotlin/no/nav/familie/ef/personhendelse/forvaltning/BehandleAutomatiskInntektsendringForvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektOppgaveService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForInntektsendringerTask.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektOppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForInntektsendringerTaskTest.kt
Opprettes nå tasks som lager oppgaver på personer med inntektsendring.
=> Oppretter nå tasks for opprettelse av inntektsendring oppgaver, lagt til task type og test

.nais/prod.yaml, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-integrasjonstest.yml
Peker på ny sqlinstans med versjon 15 av db
=> Ny db config prod
