src/main/kotlin/no/nav/familie/ef/personhendelse/handler/DodsfallHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/DøfødtBarnHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseHåndterer.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/UtflyttingHandler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/DodsfallHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/DøfødtBarnHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/LoadHandlersTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/SivilstandHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/UtflyttingHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListenerTest.kt
Endrer til å bruke interface for personhendelse i stedet for abstract då handlers ikke trenger noe forhold til sakclient, oppgave etc. Men att dette legges i en personhendelseService
Notere att det ser ut som veldig mye kode er endret i PersonhendelseHandler, det er fordi den har endringer og har endret navn. Dette er gjort i forskjellige commits sånn att diffen blir litt enklere å skjønne hvis man ser per commit
=> Personhendelse interface

src/main/kotlin/no/nav/familie/ef/personhendelse/client/ArbeidsfordelingClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/IntegrasjonstestConfig.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/config/EfSakClientMock.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt, src/test/resources/inntekt/InntekthistorikkLoennsinntektOgOffentligYtelseEksempel.json
Det er flere forbedringer som burde gjøres og som ikke er glemt. Kommer til å lage ny favro-sak, men jeg prioriterer ikke gjøre det nå, fordi det er stort sett ytelsesforbedringer:
- Sende all informasjon som trengs på kafka for å slippe kall mot ef-sak
- Sette opp scheduler som kaller automatisk (til å starte med ønsker jeg å gjøre kallet manuelt for å i større grad ha kontroll og dobbeltsjekke litt i prod)
- Batche opp personer og kjøre i parallell
=> Oppretter oppgaver ved vedtak- og inntektsendringer

src/main/kotlin/no/nav/familie/ef/personhendelse/client/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/handler/PersonhendelseService.kt
Tilretteleggjing for å fjerne toQueryParams-metoden, som fører med seg mykje unødig kompleksitet
Legg til rette for https://github.com/navikt/familie-kontrakter/pull/684
=> Definerer eksplisitt dei query-params som faktisk blir sendt inn for finnMappeRequest

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektDomain.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektHistorikkDomain.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/main/resources/db/migration/V6__add_inntekt_endret_prosent.sql, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
**Hvorfor gjøres dette?**
Ikke laget eget Favro-kort på det, men det er ønsket fra fag at det beregnes hvor mye inntekt endres i prosent, slik at de med høyest avvik på inntekt revurderes først for å unngå feilutbetalinger
=> Beregn og lagre prosentvis endring i inntekt i inntektsjekk

.deploy/preprod.yaml, .deploy/prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjerner CPU-limit

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/main/resources/db/migration/V7__ny_ytelse_type.sql, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
**Hvorfor?**
Som del av innsiktsarbeid sammen med avdelingslederne er det ønskelig at det blir tallfestet hvilke ytelser som er nye, og at alle ytelser tas med i vedtaksendringer-sjekken. Lagrer derfor ned hvilke vedtak som anses som nye. Anså det som greit at det kan bli satt flere ytelser i samme kolonne, da det bare skal brukes til å rapportere videre.
Edit: testet i preprod
=> Vedtaksendringer - lagre hvilke vedtak som er nye

src/main/kotlin/no/nav/familie/ef/personhendelse/client/SakClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektDomain.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/main/resources/db/migration/V10__inntekt_fire_mnd_tilbake.sql, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
Feilutbetaling skal beregnes for å prioritere best mulig hvilke saker som burde revurderes som følge av for høy inntekt.
Implementerer også lagring av inntekt 4 mnd tilbake, da det er ønsket fra saksbehandlere. Tilhørende PR i ef-sak: https://github.com/navikt/familie-ef-sak/pull/2449
=> Beregn feilutbetaling og lagre inntekt for 4 måneder tilbake

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/FeilutbetalingBeregningUtil.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/handler/ForelderBarnHandlerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/FeilutbetalingBeregningUtilTest.kt
Feil ved beregning av feilutbetaling, inntektsavkortning skal beregnes til månedlig for at det skal beregnes riktig.
=> Bugfix - beregning av feilutbetaling

src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt
På grunn av en problemer med db hos PDL, må de sende ut hendelser på nytt fra fredag. Ignorerer nå duplikate hendelsesIds. Kommer til å ta inn igjen denne koden etter at personhendelse har lest siste meldingen, da vi ønsker å feile dersom det skulle skje i andre tilfeller.
https://nav-it.slack.com/archives/C020Q1K6EAY/p1699349632203809
=> Ignorer duplikate hendelser

src/main/kotlin/no/nav/familie/ef/personhendelse/client/OppgaveClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
Det skal opprettes oppgaver på personer med 20 000 kr eller mer i total feilutbetaling over de fire siste månedene. I november vil det si i perioden juli til og med oktober.
Oppgavene er spesifisert slik:
Tema: Enslig mor eller far
Oppgavetype: Vurder inntekt
Gjelder: blank
Ruting: enhetsmappe 63 Inntektskontroll
Testet i preprod:
=> Opprett oppgave inntektsendringer

Dockerfile
Hvorfor trengs denne endringen ?
Det virker unødvendig å ha egen distro inkludert i docker image, da dette er overflødig og gir potensielt mange sikkerhetshull.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-16237
=> Bytter til distroless dockerimage

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerScheduler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepository.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/vedtak/EfVedtakRepositoryTest.kt
Hvorfor ? 
For å redusere potensielle feilutbetalinger skal det opprettes oppgave for inntektsendring hvis det har blitt innvilget uføretrygd, siden overgangsstønaden skal reduseres krone for krone med uføretrygd. 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20312
=> Opprette oppgave når nytt vedtak er uføretrygd

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
I starten av 2022 var det mange som fikk etterbetalinger av sykepenger, noe som gjorde at vi bestemte vi ignorerte disse da det kunne gjelde for en periode som var veldig langt tilbake i tid, da det var stort etterslep på utbetaling av sykepenger. Det er nå bestemt av funksjonelle at etterbetalinger av ytelser ikke skal ignoreres lenger.
=> Etterbetalinger skal ikke lenger ignoreres

src/main/kotlin/no/nav/familie/ef/personhendelse/configuration/KafkaConfig.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListener.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/familie/ef/personhendelse/kafka/PersonhendelseListenerTest.kt, src/test/resources/application-integrasjonstest.yml, src/test/resources/application-local.yml
Setter `auto-offset-reset: earliest` for å sikre at ingen hendelser går tapt dersom offset mangler eller blir slettet. Ulempen er at dersom det må leses fra start, kan det ta noe tid (leesah/personhendelse-topic har 30 dagers retention). Likevel anses det som akseptabelt at hendelser i verste fall leses en dag etter publisering. For kontantstøtte-vedtak-topicet, som har 60 dagers retention og relativt få hendelser, er det også uproblematisk å lese fra start om offset mistes.
**Transaksjoner**
Konfigurasjon av transaksjoner og offset-commit kan være litt forvirrende siden det finnes to forskjellige innstillinger: `enable-auto-commit: true/false` og `ackMode`. `enable-auto-commit` er en Kafka-native innstilling, mens `ackMode` er spesifikk for Spring, og de fungerer i utgangspunktet …
=> Oppdatert kafka config. Det er blant annet tydeligere hvilken config som gjelder for hvilket topic

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yaml
Denne PRen prøver å fjerne deprecated work flow variabler fra bygg og deploy taskene. NAIS har satt og `identity_provider` og `project_id` deprecated og skal fjernes, da alle setter de samme verdiene her og utledes derfor automatisk av nais-plattformen nå. Workflows med disse parameterene satt vil ikke lenger virke etter 3. mars.
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24100).
Dette er en av mange PRer der denne samme endringen gjøres for repoer tilhørende enslig-forsørger.
=> Legacy - fjerne deprecated work flow variabler fra build & deploy 

src/main/kotlin/no/nav/familie/ef/personhendelse/client/SakClient.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringerUtil.kt, src/main/resources/db/migration/V15__lagre_naavaerende_vedtak.sql, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt
Mulighet for å trigge automatisk revurdering fra både kall og scheduler. Inntil videre skal ikke den gjøre noe annet enn å logge, som del av analyse-arbeid. Dette er første steg for å se hvor mange som eventuelt ville ha vært kandidater til automatisk revurdering:
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23903)
Mange av kriteriene og informasjonen som trengs for å avgjøre om en bruker skal automatisk revurderes finnes i ef-sak, og det gjøres derfor et kall til ef-sak som skal ta seg evalueringen av dette. Tilhørende [PR i ef-sak](https://github.com/navikt/familie-ef-sak/pull/2776).
=> Delautomatisering av inntektsendring

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
Funnet ut sammen med Mirja etter gjennomgang av inntektskontroll.
=> Barnepensjon skal ikke regnes som pensjonsgivende inntekt og skal ikke slås ut i inntektskontroll

pom.xml
Nyeste versjon av deploy-steget har antakelig strengere validering. Version i imagenavnet går ikke gjennom validering i deploy fordi navnet ikke er statisk. Fikser dette.
=> Fix deploy

src/main/kotlin/no/nav/familie/ef/personhendelse/datoutil/DatoUtil.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektResponse.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
Beregner stabil inntekt uten feriepenger. Alt som er lagret i db fra før er lagret med alle type inntekter, inkludert feriepenger. 
Det må dessverre gjøres nytt kall til a-inntekt for å sjekke hva som er feriepenger, slik at man kan se om inntekt er stabil uten feriepenger. Normalt er feriepenger registrert sammen med fastlønn. En typisk feriemåned har fastlønn, feriepenger og trekk for feriepenger. Hvis feriepenger og trekk for feriepenger ikke tas med i beregningen, så står man bare igjen med fastlønn, som er det vi er ute etter. Det er typisk ikke så mange kandidater til automatisk revurdering av inntekt, så det er helt greit at det gjøres nytt kall mot a-inntekt for disse.
=> Beregn stabil inntekt uten feriepenger.

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerService.kt
Det må avklares om dette er godt nok når funksjonelle er tilbake fra ferie. Det kan hende at introduksjonsstønaden må medberegnes hvis det finnes tilfeller av brukere med inntekt ved siden av introduksjonsstønaden.
=> Ignorerer introduksjonsstoenad som inntekt, da dette ikke skal gå utover uredusert stønad

src/main/kotlin/no/nav/familie/ef/personhendelse/forvaltning/BehandleAutomatiskInntektsendringForvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektOppgaveService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/LoggInntektForPersonTask.kt
Det er behov for å se InntektResponse for gitt person for å analysere inntektsendringer. 
Alternativet er å lagre til db, men dette ses som en bedre måte fordi logger vil slettes over tid.
Testet i dev for å dobbeltsjekke at dette printes ut til securelogger.
=> Logg inntekt for person

src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/FinnPersonerMedEndringUføretrygdTask.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/IntegrasjonSpringRunnerTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/FinnPersonerMedEndringUføretrygdTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/VedtakendringUtilTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/util/JsonFilUtil.kt, src/test/resources/inntekt/InntektUføretrygdUtenEndring.json
Tidligere kode gjorde at den bare tok med første innslag av måned, selv om det fantes flere, og beregnet derfor uføretrygd til 0 for to måneder siden.
=> En bugfix som tar høyde for at det kan finnes flere innslag av samme måned i inntektsresponse

src/main/kotlin/no/nav/familie/ef/personhendelse/forvaltning/BehandleAutomatiskInntektsendringForvaltningsController.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepository.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerScheduler.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/endring/FeilutbetalingBeregningUtil.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/endring/Grunnbeløp.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/endring/InntektsendringerService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/endring/RevurderAutomatiskPersonerMedInntektsendringerTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/FinnPersonerFyltTjueFemArbeidsavklaringspengerTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/FinnPersonerMedEndringUføretrygdTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/InntektOppgaveService.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/OpprettOppgaverForArbeidsavklaringspengerEndringerTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/OpprettOppgaverForInntektsendringerTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/OpprettOppgaverForNyeVedtakUføretrygdTask.kt, src/main/kotlin/no/nav/familie/ef/personhendelse/inntekt/oppgave/OpprettOppgaverForUføretrygdsendringerTask.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/FeilutbetalingBeregningUtilTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/FinnPersonerFyltTjueFemArbeidsavklaringspengerTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/FinnPersonerMedEndringUføretrygdTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/GrunnbeløpTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektOgVedtakEndringTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektOppgaveServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerRepositoryTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/InntektsendringerServiceTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForArbeidsavklaringspengerEndringerTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForInntektsendringerTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForNyeVedtakUføretrygdTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/OpprettOppgaverForUføretrygdsendringerTaskTest.kt, src/test/kotlin/no/nav/familie/ef/personhendelse/inntekt/RevurderAutomatiskPersonerMedInntektsendringerTaskTest.kt
Flyttet tasks og service tilknyttet endring og oppgave til egen mappe. Blir mer ryddig ettersom inntekt pakken begynte å bli stor.
=> FLyttet tasks og service tilknyttet endring og oppgave til egen mappe

.nais/dev.yaml, src/main/resources/application-dev.yml
Testet med ny instans i preprod, og det krever ny db-config. Replikering til ny db instans er bare gjort i dev, og det er derfor bare endret config for dev.
=> Bruk ny db-config i dev
